import { useEffect, useState } from 'react';

import Head from 'next/head';
import Link from 'next/link';

import { Navbar } from '../components/Navbar';
import { SlideButtons } from '../components/SlideButtons';

import { slideContent } from '../data';
import { aboutContent } from '../data';

import styles from '../styles/Home.module.scss';

export default function Home() {

  const [isToggleActive, setIsToggleActive] = useState(false);
  const [currentSlideContent, setCurrentSlideContent] = useState(slideContent[0]);
  const [image, setImage] = useState('');

  useEffect(()=>{
    ChooseImageByScreenSize();
  }, [currentSlideContent]);

  const ChooseImageByScreenSize = () =>{
    const screenSize = window.innerWidth;

    if(screenSize < 1024){
      setImage(currentSlideContent.mobileImage)
    }
    else{
      setIsToggleActive(false);
      setImage(currentSlideContent.desktopImage);
    }
  }

  useEffect(()=>{
    window.addEventListener('resize', ChooseImageByScreenSize);
    return ()=>{
      window.removeEventListener('resize', ChooseImageByScreenSize);
    }
  });

  const previousSlide = () => {
    const newID = currentSlideContent.id - 1;
    
    newID < 0?
    setCurrentSlideContent(slideContent[slideContent.length - 1])
    :
    setCurrentSlideContent(slideContent[newID]);
  }
  
  const nextSlide = () => {
    const newID = currentSlideContent.id + 1;
    
    newID == slideContent.length?
    setCurrentSlideContent(slideContent[0])
    :
    setCurrentSlideContent(slideContent[newID])
  }

  return (
    <main className={styles.wrapper}>
      <Head>
        <title>Room Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Spartan:wght@500;600;700&display=swap" rel="stylesheet"/>
      </Head>

      <header className={styles.header}>
        <section
          className={styles.navbar_wrapper}
          style={{backgroundImage:`url("${image}")`}}
        >

          <Navbar
            isToggleActive={isToggleActive}
            setIsToggleActive={setIsToggleActive}
          />

          <div className={styles.slide_buttons_navbar}>
            <SlideButtons
              previousSlide={previousSlide}
              nextSlide={nextSlide} />
          </div>
        </section>

        <article className={styles.slide_text_content}>
          <div className={styles.container}>
            <h1 className={styles.slide_text_content_title}>  {currentSlideContent.title}
            </h1>
            
            <p className={styles.slide_text_content_description}>{currentSlideContent.description}
            </p>
            
            <Link href='#'>
              <a className={styles.cta_button}>
                <span>Shop now</span>
                <img src='/images/icon-arrow.svg' alt='Shop now!'/>
              </a>
            </Link>
          </div>
          
          <div className={styles.slide_buttons_article}>
            <SlideButtons
              previousSlide={previousSlide}
              nextSlide={nextSlide} />
          </div>
        </article>
      </header>

      <section className={styles.about}>
        <div className={styles.about_dark_image}></div>

        <div className={styles.about_text_content}>
          <div className={styles.container}>
            <h2 className={styles.about_text_content_title}>
              {aboutContent[0].title}
            </h2>
            <p className={styles.about_text_content_description}>
              {aboutContent[0].description}
            </p>
          </div>
        </div>

        <div className={styles.about_light_image}></div>
      </section>

    </main>
  )
}
